import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Patua_One } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local"
import { Toaster } from "sonner";

const coffee = localFont( {
  src: "coffee-rg.otf"
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const patua = Patua_One({
  subsets: ["latin"],
  weight: "400", // only available weight
  variable: "--font-patua",
  display: "swap",
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chords & Coffee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Patua+One&display=swap" rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${coffee.className} antialiased ${patua.variable}`}
      >
        {children}
        <Toaster></Toaster>
      </body>
    </html>
  );
}
